# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from llmruntime.v1 import llm_pb2 as llmruntime_dot_v1_dot_llm__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in llmruntime/v1/llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LlmRuntimeStub(object):
    """A simple, provider-agnostic LLM gateway.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/llmruntime.v1.LlmRuntime/Generate',
                request_serializer=llmruntime_dot_v1_dot_llm__pb2.GenerateRequest.SerializeToString,
                response_deserializer=llmruntime_dot_v1_dot_llm__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.GenerateStream = channel.unary_stream(
                '/llmruntime.v1.LlmRuntime/GenerateStream',
                request_serializer=llmruntime_dot_v1_dot_llm__pb2.GenerateRequest.SerializeToString,
                response_deserializer=llmruntime_dot_v1_dot_llm__pb2.GenerateChunk.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/llmruntime.v1.LlmRuntime/Health',
                request_serializer=llmruntime_dot_v1_dot_llm__pb2.HealthRequest.SerializeToString,
                response_deserializer=llmruntime_dot_v1_dot_llm__pb2.HealthResponse.FromString,
                _registered_method=True)


class LlmRuntimeServicer(object):
    """A simple, provider-agnostic LLM gateway.
    """

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=llmruntime_dot_v1_dot_llm__pb2.GenerateRequest.FromString,
                    response_serializer=llmruntime_dot_v1_dot_llm__pb2.GenerateResponse.SerializeToString,
            ),
            'GenerateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateStream,
                    request_deserializer=llmruntime_dot_v1_dot_llm__pb2.GenerateRequest.FromString,
                    response_serializer=llmruntime_dot_v1_dot_llm__pb2.GenerateChunk.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=llmruntime_dot_v1_dot_llm__pb2.HealthRequest.FromString,
                    response_serializer=llmruntime_dot_v1_dot_llm__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llmruntime.v1.LlmRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llmruntime.v1.LlmRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LlmRuntime(object):
    """A simple, provider-agnostic LLM gateway.
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmruntime.v1.LlmRuntime/Generate',
            llmruntime_dot_v1_dot_llm__pb2.GenerateRequest.SerializeToString,
            llmruntime_dot_v1_dot_llm__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/llmruntime.v1.LlmRuntime/GenerateStream',
            llmruntime_dot_v1_dot_llm__pb2.GenerateRequest.SerializeToString,
            llmruntime_dot_v1_dot_llm__pb2.GenerateChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmruntime.v1.LlmRuntime/Health',
            llmruntime_dot_v1_dot_llm__pb2.HealthRequest.SerializeToString,
            llmruntime_dot_v1_dot_llm__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
