# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llmruntime/v1/llm.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'llmruntime/v1/llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17llmruntime/v1/llm.proto\x12\rllmruntime.v1\"\xb8\x02\n\x0fGenerateRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x0e\n\x06system\x18\x03 \x01(\t\x12<\n\x07options\x18\x04 \x03(\x0b\x32+.llmruntime.v1.GenerateRequest.OptionsEntry\x12\x11\n\tjson_mode\x18\x05 \x01(\x08\x12\x13\n\x0bjson_schema\x18\x06 \x01(\t\x12\x12\n\nmax_tokens\x18\x07 \x01(\x05\x12\x13\n\x0btemperature\x18\x08 \x01(\x02\x12\x0f\n\x07user_id\x18\t \x01(\t\x12\x12\n\nrequest_id\x18\n \x01(\t\x12\x12\n\ntimeout_ms\x18\x0b \x01(\x05\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"l\n\x10GenerateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x10\n\x08provider\x18\x03 \x01(\t\x12\x15\n\rfinish_reason\x18\x04 \x01(\t\x12\x12\n\nrequest_id\x18\x05 \x01(\t\"d\n\rGenerateChunk\x12\r\n\x05\x64\x65lta\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x10\n\x08provider\x18\x03 \x01(\t\x12\x0c\n\x04\x64one\x18\x04 \x01(\x08\x12\x15\n\rfinish_reason\x18\x05 \x01(\t\"\x0f\n\rHealthRequest\"Q\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x18\n\x10provider_default\x18\x02 \x01(\t\x12\x15\n\rmodel_default\x18\x03 \x01(\t2\xf2\x01\n\nLlmRuntime\x12K\n\x08Generate\x12\x1e.llmruntime.v1.GenerateRequest\x1a\x1f.llmruntime.v1.GenerateResponse\x12P\n\x0eGenerateStream\x12\x1e.llmruntime.v1.GenerateRequest\x1a\x1c.llmruntime.v1.GenerateChunk0\x01\x12\x45\n\x06Health\x12\x1c.llmruntime.v1.HealthRequest\x1a\x1d.llmruntime.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llmruntime.v1.llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST_OPTIONSENTRY']._loaded_options = None
  _globals['_GENERATEREQUEST_OPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_GENERATEREQUEST']._serialized_start=43
  _globals['_GENERATEREQUEST']._serialized_end=355
  _globals['_GENERATEREQUEST_OPTIONSENTRY']._serialized_start=309
  _globals['_GENERATEREQUEST_OPTIONSENTRY']._serialized_end=355
  _globals['_GENERATERESPONSE']._serialized_start=357
  _globals['_GENERATERESPONSE']._serialized_end=465
  _globals['_GENERATECHUNK']._serialized_start=467
  _globals['_GENERATECHUNK']._serialized_end=567
  _globals['_HEALTHREQUEST']._serialized_start=569
  _globals['_HEALTHREQUEST']._serialized_end=584
  _globals['_HEALTHRESPONSE']._serialized_start=586
  _globals['_HEALTHRESPONSE']._serialized_end=667
  _globals['_LLMRUNTIME']._serialized_start=670
  _globals['_LLMRUNTIME']._serialized_end=912
# @@protoc_insertion_point(module_scope)
